-- ==========================================================
-- Supabase (PostgreSQL) Database Schema
-- สำหรับระบบจองวันกิจกรรม EventPass
-- นำโค้ดชุดนี้ไปวางในเมนู SQL Editor ใน Supabase Dashboard แล้วกด Run ได้เลยครับ
-- ==========================================================

-- 1. สร้างตาราง events (กิจกรรม)
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  event_date DATE NOT NULL,
  location TEXT NOT NULL,
  price TEXT DEFAULT 'ฟรีไม่มีค่าใช้จ่าย',
  status TEXT DEFAULT 'published',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. สร้างตาราง event_slots (รอบเวลาและที่นั่ง)
CREATE TABLE IF NOT EXISTS public.event_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
  time_slot TEXT NOT NULL,
  capacity INT NOT NULL DEFAULT 50,
  booked INT NOT NULL DEFAULT 0
);

-- 3. สร้างตาราง bookings (ข้อมูลการจอง)
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT NOT NULL UNIQUE,
  event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
  slot_id BIGINT REFERENCES public.event_slots(id) ON DELETE CASCADE,
  guest_name TEXT NOT NULL,
  guest_email TEXT NOT NULL,
  guest_phone TEXT NOT NULL,
  seats INT NOT NULL DEFAULT 1,
  checked_in BOOLEAN NOT NULL DEFAULT FALSE,
  checked_in_at TIMESTAMPTZ,
  booked_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ตั้งค่า Row Level Security (RLS) เพื่อให้หน้าเว็บอ่านและบันทึกข้อมูลได้
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- นโยบายเปิดให้อ่านข้อมูลกิจกรรมและรอบเวลาได้ทุกคน (Public Read)
CREATE POLICY "Allow public read on events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public read on event_slots" ON public.event_slots FOR SELECT USING (true);
CREATE POLICY "Allow public insert on events" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on event_slots" ON public.event_slots FOR UPDATE USING (true);

-- นโยบายให้ผู้ใช้ทั่วไปจองและค้นหาการจองได้
CREATE POLICY "Allow public read on bookings" ON public.bookings FOR SELECT USING (true);
CREATE POLICY "Allow public insert on bookings" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on bookings" ON public.bookings FOR UPDATE USING (true);

-- 5. เพิ่มข้อมูลตัวอย่างเริ่มต้น
INSERT INTO public.events (id, title, category, description, image_url, event_date, location, price)
VALUES
(1, 'AI & Modern Tech Summit 2026', 'เทคโนโลยี', 'งานสัมมนาเจาะลึกปัญญาประดิษฐ์และเทคโนโลยีแห่งอนาคต พบกับวิทยากรระดับแนวหน้าจากองค์กรชั้นนำ', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', '2026-09-15', 'True Digital Park, Grand Hall ชั้น 3 กรุงเทพฯ', 'ฟรีไม่มีค่าใช้จ่าย'),
(2, 'Hands-on UI/UX & Design Systems Workshop', 'เวิร์กช็อป', 'เวิร์กช็อปเชิงปฏิบัติการสร้าง Design System ตั้งแต่ศูนย์จนถึงระดับโปรดักชัน พร้อมทดลองใช้งานกับทีมจริง', 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80', '2026-09-22', 'TCDC Charoenkrung (ศูนย์สร้างสรรค์งานออกแบบ)', 'ฟรีไม่มีค่าใช้จ่าย'),
(3, 'Indie Music Under The Stars Concert', 'คอนเสิร์ต', 'เทศกาลดนตรีอะคูสติกยามเย็นกลางสวนสวย ฟังเพลงสบายๆ จากศิลปินอินดี้ชื่อดังในบรรยากาศสุดชิล', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80', '2026-09-28', 'สวนป่าเบญจกิติ ลานกิจกรรมกลางแจ้ง', 'ฟรีไม่มีค่าใช้จ่าย')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.event_slots (id, event_id, time_slot, capacity, booked)
VALUES
(1, 1, '09:00 - 12:00 น. (รอบเช้า)', 60, 42),
(2, 1, '13:30 - 16:30 น. (รอบบ่าย)', 60, 58),
(3, 2, '10:00 - 16:00 น. (เต็มวัน)', 30, 28),
(4, 3, '17:30 - 21:30 น.', 150, 95)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.bookings (id, booking_code, event_id, slot_id, guest_name, guest_email, guest_phone, seats, checked_in)
VALUES
(1, 'EVT-2609-1001', 1, 1, 'สมชาย ใจดี', 'somchai@example.com', '081-234-5678', 2, false),
(2, 'EVT-2609-1002', 3, 4, 'กานดา สดใส', 'kanda@example.com', '089-876-5432', 1, true)
ON CONFLICT (id) DO NOTHING;
